### PR TITLE
added file ext adding to loadEnsemble

### PR DESCRIPTION
**Pull request by jamesmkrieger**
Seeing as they're saved like that, it makes it easier to be able to load like that too.

### CODE REVIEW

**Comment by SHZ66** [comment]
Unlike saving files where extensions can be added automatically,

**Comment by jamesmkrieger** [comment]
Why is this reopened?

**Comment by SHZ66** [comment]
> Why is this reopened?

I wasn't sure about the change and wanted to comment but decided to do that later, and then accidentally clicked on the close button.

**Comment by jamesmkrieger** [comment]
ok. It's exactly copied from saveEnsemble so should we change it there too?

**Pull request closed without merging**
