### PR TITLE
bug fix to matchModes 

### PR DESCRIPTION
**Pull request by jamesmkrieger**
so we can get indices without starting with modesets

Before, it would fail because ANM objects don't have getIndices. Now it can cope with that.

### CODE REVIEW

**Comment by SHZ66** [comment]
Overall looks good to me, but I think we can either use a more specific try-except on AttributeError, or use hasattr to detect if the modeset has getIndices or not.

**Comment by jamesmkrieger** [comment]
Like this?

**Comment by SHZ66** [comment]
Yes. If this is bug-free then feel free to merge it.

**Comment by jamesmkrieger** [comment]
ok, I'll check it a little more I guess

**Pull request merged**
