### PR TITLE
A few minor bug fixes

### PR DESCRIPTION
**Pull request by jamesmkrieger**
I decided to separate my branches and this pull request from the commits about building biomolecular assemblies because we still need to check that what I did there is right.

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
My fix on showDomainBar isn't quite right. If no loc is specified then we have a problem of a half-unit shift.

**Comment by jamesmkrieger** [comment]
I think everything is good here too. I can split it into fixes for separate issues if you prefer. I just found this way to do it much more cleanly and easily: https://gist.github.com/Loilo/930f141d9acf89e9e734ffa042acd750

**Comment by SHZ66** [comment]
> I think everything is good here too. I can split it into fixes for separate issues if you prefer. I just found this way to do it much more cleanly and easily: https://gist.github.com/Loilo/930f141d9acf89e9e734ffa042acd750

Ok. I just think, to be safe, we probably should review the code sometime together. Nice useful link by the way - yes, in principle we should have separate pull requests for different problems - but I think this one is ok, no need to separate it.

**Comment by jamesmkrieger** [comment]
ok

**Pull request merged**
