### PR TITLE
Fix IndexError exception when local pairwise alignment produces 0 alignments

### PR DESCRIPTION
**Pull request by ArturKlauser**
It is possible for local alignment between pairs of chains to produce an empty list of alignments, resulting in an IndexError in the current code. This patch takes care of this issue.

Original error:

> File .../prody/proteins/compare.py:796, in getAlignedMatch(ach, bch)
>     789 else:
>     790     alignment = pairwise2.align.globalms(ach.getSequence(),
>     791                                          bch.getSequence(),
>     792                                          MATCH_SCORE, MISMATCH_SCORE,
>     793                                          GAP_PENALTY, GAP_EXT_PENALTY,
>     794                                          one_alignment_only=1)
> --> 796 this = alignment[0][0]
>     797 that = alignment[0][1]
>     798 amatch = []
> 
> IndexError: list index out of range
>

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by jamesmkrieger** [comment]
Why do you return if you get an index error?

**Comment by ArturKlauser** [comment]
I return an empty alignment in that case. Are there other reasonable options?

**Comment by jamesmkrieger** [comment]
It depends on what upstream functions are expecting. It looks like the only one at the moment is matchChains and that would handle it ok. You'd get 0 seqid and 0 coverage. 

One alternative would be to raise an error, but I guess that's not actually a reasonable option.

Probably, the best thing to do is to keep what you have but raise a warning with LOGGER.warning

**Comment by ArturKlauser** [comment]
Warning sounds good. I updated the PR accordingly.

**Comment by jamesmkrieger** [comment]
Thanks

**Pull request merged**
