### PR TITLE
bug fixes to showProjection around colors

### PR DESCRIPTION
**Pull request by jamesmkrieger**
An update to matplotlib means cmap changed and it doesn't have an attribute `.color`. This is the fix to the problem. It wasn't necessary to change anything else.

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
This still doesn't work.

**Comment by jamesmkrieger** [comment]
This now works in 2D and 3D:
time-colored_run1_pca_proj3d
time-colored_run1_pca_proj2d

It raises lots of these warnings in 2D though:
```'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.```

**Comment by jamesmkrieger** [comment]
The 2D case gives lots of these warnings but otherwise everything is good.
```'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.```

**Comment by SHZ66** [comment]
```
from numbers import Number

isinstance(3.0, Number)
```

**Comment by SHZ66** [comment]
[matplotlib.pyplot.scatter](https://matplotlib.org/3.2.0/api/_as_gen/matplotlib.pyplot.scatter.html)

**Pull request merged**
