### PR TITLE
Fix clustenm saving and loading

### PR DESCRIPTION
**Pull request by jamesmkrieger**
There's a problem with _cc if it's not defined. 

Then topology and positions don't work for loading because they require openmm. I guess we could add an import though instead

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
What this supports now is to be able to load and save again clustenm objects in another environment that lacks openmm

**Comment by atbogetti** [comment]
Hey @jamesmkrieger, I think this should be working, but I cannot get ClustENM to work on a simple system in ProDy 2.4.1. On the most recent conda release version (2.4.0) everything works fine. However, using the version from GitHub (2.4.1) I am getting an error.

The code I am running is:
```
from prody import *

mol = parsePDB("1ake_eq.pdb")
clustenm = ClustENM()
clustenm.setAtoms(mol)
clustenm.run(cutoff=15, n_modes=5, rmsd=1, n_gens=5, 
             n_confs=10, maxclust=5, sim=False, 
             solvent="imp", platform='CPU')
saveEnsemble(clustenm)
```
and I'm getting:
```
(prody-git) anthony@laufer-abogetti:~/Documents/prody-devel/clustenm_saving_no_openmm$ python ClustENM.py 
@> 3341 atoms and 1 coordinate set(s) were parsed in 0.01s.
@> Fixing the structure ...
@> 3341 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> The structure was fixed in 0.27s.
@> Kirchhoff was built in 0.01s.
@> Generation 0 ...
@> Minimization in generation 0 ...
@> Completed in 1.58s.
@> #-------------------/*\-------------------#
@> Generation 1 ...
@> Sampling conformers in generation 1 ...
@> Hessian was built in 0.03s.
Traceback (most recent call last):
  File "ClustENM.py", line 8, in <module>
    clustenm.run(cutoff=15, n_modes=5, rmsd=1, n_gens=5, n_confs=10, maxclust=5, sim=False, solvent="imp", platform='CPU')
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/dynamics/clustenm.py", line 1206, in run
    confs, weights = self._generate(start_confs)
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/dynamics/clustenm.py", line 676, in _generate
    tmp = [sample_method(conf) for conf in confs]
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/dynamics/clustenm.py", line 676, in <listcomp>
    tmp = [sample_method(conf) for conf in confs]
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/dynamics/clustenm.py", line 527, in _sample
    anm_cg.calcModes(self._n_modes, turbo=self._turbo,
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/dynamics/anm.py", line 230, in calcModes
    values, vectors, vars = solveEig(self._hessian, n_modes=n_modes, zeros=zeros, 
  File "/home/anthony/apps/miniforge3/envs/prody-git/lib/python3.8/site-packages/ProDy-2.4.1-py3.8-linux-x86_64.egg/prody/utilities/eigtools.py", line 90, in solveEig
    if nproc > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```
Any ideas what could be causing this?

Also of note is I have to run with OpenMM version < 8.0 since there were some updates to the unit definitions that cause the energy minimization/heating checks to fail.

**Comment by atbogetti** [comment]
@jamesmkrieger The stated error is now fixed with your code changes, I will go ahead and approve this PR. This one (like #1872, also works with 2.4.0 but not the Git version.

**Review by atbogetti — APPROVED** [review]

**Comment by jamesmkrieger** [comment]
I think that’s the pyparsing version issue

**Comment by jamesmkrieger** [comment]
I wonder if we broke something since 2.4.0

**Pull request merged**
