### PR TITLE
added packmol chain renumbering

### LINKED ISSUE #1192: Add option to parse alternating chain labels as separate chains for PDB parser
Hello, our research group uses ProDy to parse PDBs during input generation for our [coarse grained MD simulation package](https://github.com/sosnicklab/upside-md). We are trying to go to bigger systems with 100s of protein molecules. To compose the initial configuration of these systems and pack our simulation box, we are hoping to use [Packmol](http://m3g.iqm.unicamp.br/packmol/examples.shtml), which provides an option to output PDB structures with alternating chain labels (ABABABA...) to denote different molecules (considering that the PDB format is limited in the number of chains).

Is it possible to add an option to ProDy's PDB parser to recognize alternating chain labels as completely new chains? Thank you.

### PR DESCRIPTION
**Pull request by jamesmkrieger**
This is alternative fix to close #1192.

It is much cleaner than the previous ones because it has a function in utilities/misctools.py rather than repeated code and is also optional and only activated when the kwarg packmol is set to True. 

The result for the PDB file in #1192 is as follows:

```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('1IYT_multi.pdb')
@> 3180 atoms and 1 coordinate set(s) were parsed in 0.04s.

In [3]: list(ag.getHierView())
Out[3]: 
[<Chain: A from 1IYT_multi (42 residues, 1908 atoms)>,
 <Chain: B from 1IYT_multi (42 residues, 1272 atoms)>]

In [4]: ag = parsePDB('1IYT_multi.pdb', packmol=True)
@> 3180 atoms and 1 coordinate set(s) were parsed in 0.03s.

In [5]: list(ag.getHierView())
Out[5]: 
[<Chain: 0 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 1 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 2 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 3 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 4 from 1IYT_multi (42 residues, 636 atoms)>]
```

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
It now works for cases with more than 100 chains as well. I created a test set as follows:

```
$ head -n 2549 1IYT_multi.pdb > 1IYT_multi_clipped.pdb
$ for i in `seq 1 100`; do tail -n +6 1IYT_multi_clipped.pdb >> 1IYT_multi_multi.pdb; done
$ ipython
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('1IYT_multi_multi.pdb')
@> 532196 atoms and 1 coordinate set(s) were parsed in 5.25s.

In [3]: writePDB('1IYT_multi_multi_renum.pdb', ag)
@> WARNING Indices are exceeding 99999 and hexadecimal format is being used
Out[3]: '1IYT_multi_multi_renum.pdb'
```

The test on this then shows that it worked:
```
$ ipython
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('1IYT_multi_multi_renum.pdb', packmol=True)
@> 532196 atoms and 1 coordinate set(s) were parsed in 5.17s.

In [3]: list(ag.getHierView())[:10]
Out[3]: 
[<Chain: 0 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 1 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 2 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 3 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 4 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 5 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 6 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 7 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 8 from 1IYT_multi_multi_renum (42 residues, 641 atoms)>,
 <Chain: 9 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>]

In [4]: list(ag.getHierView())[-10:]
Out[4]: 
[<Chain: 826 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 827 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 828 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 829 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 830 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 831 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 832 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 833 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 834 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>,
 <Chain: 835 from 1IYT_multi_multi_renum (42 residues, 636 atoms)>]

In [5]: ag.getChids()
Out[5]: array(['0', '0', '0', ..., '835', '835', '835'], dtype='<U3')
```

**Comment by yihengwuKP** [comment]
Just reporting here the `packmol` argument seems not to work for my case: `prody --version=1.11, python 2.7.15` (result of `conda update prody`)
When I run the following codes, I would always get `1IYT_multi.pdb` parsed as 5 chains whether I use `packmol=True` or not. Personally this is great for my purpose, since I want this feature; just report it here since it seems to be different than what you are showing.
```python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from prody import *

In [2]: ag = parsePDB('1IYT_multi.pdb')
@> 3180 atoms and 1 coordinate set(s) were parsed in 0.03s.

In [3]: list(ag.getHierView())
Out[3]: 
[<Chain: 0 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 1 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 2 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 3 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 4 from 1IYT_multi (42 residues, 636 atoms)>]

In [4]: ag = parsePDB('1IYT_multi.pdb', packmol=True)
@> 3180 atoms and 1 coordinate set(s) were parsed in 0.02s.

In [5]: list(ag.getHierView())
Out[5]: 
[<Chain: 0 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 1 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 2 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 3 from 1IYT_multi (42 residues, 636 atoms)>,
 <Chain: 4 from 1IYT_multi (42 residues, 636 atoms)>]

```

**Comment by jamesmkrieger** [comment]
You need to use a later version of ProDy than that. 2.0 from PyPI (downloaded via pip) may work but otherwise please get the GitHub version and also use pip to install it

**Comment by yihengwuKP** [comment]
I see, thanks for your explaining!

**Comment by jamesmkrieger** [comment]
you're welcome

**Pull request merged**
