### PR TITLE
Streamline fixer and water filter for multiple structures

### PR DESCRIPTION
**Pull request by jamesmkrieger**
1. Added a function fixStructuresMissingAtoms for applying addMissingAtoms to many structures
2. Added a function filterStructuresWithoutWater to filter structure without water or with not enough water

This allows us to run the following pipeline:
```
In [1]: from prody import *

In [2]: pdbids = ['5UOJ', '1A9U', '1BL6', '1BL7', '1BMK', '1DI9', '1IAN']

In [3]: infiles = fetchPDB(pdbids, compressed=False)

In [4]: new_pdbids = fixStructuresMissingAtoms(infiles, method='pdbfixer')
@> WARNING outfile addH_5uoj.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1a9u.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bl6.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bl7.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bmk.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1di9.pdb already exists, so returning it. Set overwrite=True to overwrite it
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
@> Hydrogens were added to the structure. New structure is saved as addH_1ian.pdb.

In [5]: structures = parsePDB(new_pdbids)
@> 7 PDBs were parsed in 0.38s.         l

In [6]: new_structures = filterStructuresWithoutWater(structures, 200)
@> WARNING addH_1bl7 doesn't contain enough water molecules (171)
@> WARNING addH_1di9 doesn't contain enough water molecules (183)
@> WARNING addH_1ian doesn't contain water molecules
```

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
Now, we can do the opposite workflow where we save time and only fix structures after filtering:
```
In [1]: from prody import *

In [2]: pdbids = ['5UOJ', '1A9U', '1BL6', '1BL7', '1BMK', '1DI9', '1IAN', '1KV1']

In [3]: infiles = fetchPDB(pdbids, compressed=False)

In [4]: structures = parsePDB(infiles)
@> 8 PDBs were parsed in 0.43s.    

In [5]: new_structures = filterStructuresWithoutWater(structures, 70, filenames=infiles)
@> WARNING 1ian doesn't contain water molecules
@> WARNING 1di9 doesn't contain enough water molecules (61)
@> WARNING 1bl7 doesn't contain enough water molecules (57)

In [6]: new_structures
Out[6]: 
[<AtomGroup: 5uoj (3138 atoms)>,
 <AtomGroup: 1a9u (2950 atoms)>,
 <AtomGroup: 1bl6 (2927 atoms)>,
 <AtomGroup: 1bmk (2950 atoms)>,
 <AtomGroup: 1kv1 (2759 atoms)>]

In [7]: infiles
Out[7]: ['5uoj.pdb', '1a9u.pdb', '1bl6.pdb', '1bmk.pdb', '1kv1.pdb']

In [8]: new_pdbids = fixStructuresMissingAtoms(infiles, method='pdbfixer')
@> WARNING outfile addH_5uoj.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1a9u.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bl6.pdb already exists, so returning it. Set overwrite=True to overwrite it
@> WARNING outfile addH_1bmk.pdb already exists, so returning it. Set overwrite=True to overwrite it
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
@> Hydrogens were added to the structure. New structure is saved as addH_1kv1.pdb.

In [9]: structures = parsePDB(new_pdbids)
@> 5 PDBs were parsed in 0.29s.         

In [10]: structures
Out[10]: 
[<AtomGroup: addH_5uoj (6656 atoms)>,
 <AtomGroup: addH_1a9u (5955 atoms)>,
 <AtomGroup: addH_1bl6 (5896 atoms)>,
 <AtomGroup: addH_1bmk (5957 atoms)>,
 <AtomGroup: addH_1kv1 (5585 atoms)>]
```

**Comment by jamesmkrieger** [comment]
We can also avoid using parsePDB again in the second last step by replacing it with the following:
```
In [16]:     for i, file in enumerate(align_files):
    ...:         print('\n', file, '\n')
    ...:         atoms = structures[i]
    ...:         waterBridges = calcWaterBridges(atoms)
    ...:         savePDBWaterBridges(waterBridges, atoms, 'wb_'+file)
    ...: 

 align2__addH_1a9u.pdb 

@> 66 water bridges detected using method chain.
@> ARG1 NH1_20 A PHE4 N_54 A 4.905458286439708 1 ['B_6194']
@> TYR5 O_79 A GLN7 NE2_133 A 5.572107769955638 1 ['B_5849']
@> TYR5 OH_93 A GLN21 OE1_381 A 4.390322197743581 1 ['B_5897']
@> TYR5 OH_93 A ASN22 N_385 A 4.517956728433774 1 ['B_5897']
@> LEU9 O_156 A TRP14 NE1_252 A 4.1232832791356975 1 ['B_5765']
@> ILE13 N_220 A LYS50 NZ_792 A 4.230241955255041 1 ['B_6200']
@> GLU18 N_308 A ARG19 N_323 A 2.7925389880895146 1 ['B_6011']
@> GLN21 OE1_381 A ASN22 N_385 A 4.316508774461138 1 ['B_5897']
@> LYS49 NZ_770 A GLU67 OE1_1095 A 5.622123620127897 1 ['B_6266']
@> LEU51 N_796 A ASP97 OD1_1596 A 6.281676607403468 1 ['B_5534']
@> LEU51 N_796 A VAL98 N_1598 A 4.803524539335672 1 ['B_5534']
@> ARG53 NE_841 A GLN56 N_884 A 6.003285350539321 1 ['B_5900']
@> ARG53 NE_841 A PHE55 N_864 A 5.989393458439677 1 ['B_5900']
@> ARG53 NE_841 A ASN96 OD1_1582 A 3.9942401029482455 1 ['B_5900']
@> PHE55 N_864 A GLN56 N_884 A 2.7871291681585197 1 ['B_5900']
@> PHE55 N_864 A ASN96 OD1_1582 A 4.974223356464809 1 ['B_5900']
@> GLN56 N_884 A ASN96 OD1_1582 A 6.230203929246622 1 ['B_5900']
@> ILE58 N_912 A ILE59 N_931 A 2.7490105492704084 1 ['B_6134']
@> LYS62 NZ_995 A ARG66 NH2_1079 A 4.104950426010039 1 ['B_5864']
@> LYS62 NZ_995 A TRP327 NE1_5262 A 6.098822919219738 2 ['B_5597', 'B_6173']
@> LYS62 NZ_995 A LEU322 N_5165 A 7.473861920051772 2 ['B_5597', 'B_6173']
@> ARG69 O_1121 A ARG69 NE_1131 A 4.556645476663734 1 ['B_5888']
@> MET74 O_1222 A HIS76 N_1256 A 4.273036976203226 1 ['B_5822']
@> ASN78 ND2_1299 A GLN129 NE2_2120 A 3.424751815825492 1 ['B_5963']
@> THR87 O_1435 A ALA89 O_1463 A 3.779688082368703 1 ['B_5786']
@> THR87 OG1_1438 A GLU94 O_1542 A 5.6032692243011155 1 ['B_6254']
@> THR87 OG1_1438 A ASN96 N_1572 A 4.739915716550245 1 ['B_6254']
@> THR87 OG1_1438 A ASP97 N_1586 A 4.3714605110877995 1 ['B_6254']
@> GLU94 O_1542 A ASN96 N_1572 A 3.2724603893706634 1 ['B_6254']
@> GLU94 O_1542 A ASP97 N_1586 A 5.378985870961179 1 ['B_6254']
@> ASN96 N_1572 A ASP97 N_1586 A 2.802672653022467 1 ['B_6254']
@> ASP97 OD1_1596 A VAL98 N_1598 A 4.607886391828687 1 ['B_5534']
@> ASN110 ND2_1796 A TYR178 OH_2919 A 5.250788988333089 1 ['B_6056']
@> ARG132 O_2166 A PRO308 O_4960 A 4.8351264719756815 1 ['B_5834']
@> ARG132 O_2166 A PRO308 N_4956 A 5.99769872534458 1 ['B_5834']
@> ILE143 N_2342 A ARG145 NH2_2399 A 5.018384002843943 1 ['B_6062']
@> ARG145 O_2383 A ARG179 NH1_2939 A 2.956793702644812 1 ['B_5930']
@> LEU147 N_2414 A ASP195 OD1_3203 A 4.94011639538989 1 ['B_5855']
@> ALA174 N_2828 A THR175 N_2838 A 2.8704872408704447 1 ['B_5870']
@> THR175 OG1_2846 A ARG179 NH1_2939 A 4.921671057679497 1 ['B_5582']
@> TYR178 OH_2919 A GLU205 OE2_3353 A 3.172357010173982 1 ['B_5573']
@> ARG179 O_2926 A GLN221 NE2_3599 A 4.173794915900874 1 ['B_5861']
@> ARG179 O_2926 A TRP197 NE1_3237 A 3.5636999031905043 1 ['B_5861']
@> ALA180 N_2945 A SER198 OG_3257 A 4.876857184704099 1 ['B_5903']
@> ALA180 N_2945 A VAL194 O_3182 A 4.723038111216126 1 ['B_5903']
@> MET188 SD_3089 A SER283 OG_4589 A 4.328344025144034 1 ['B_6104']
@> MET188 SD_3089 A SER283 N_4580 A 5.848245035906079 1 ['B_6104']
@> ASN191 N_3132 A SER283 OG_4589 A 5.077150578818785 1 ['B_5894']
@> VAL194 O_3182 A SER198 OG_3257 A 3.3531222763269404 1 ['B_5903']
@> TRP197 NE1_3237 A GLN221 NE2_3599 A 6.137263315191876 1 ['B_5861']
@> CYS201 O_3287 A LEU212 N_3451 A 5.015615316190028 1 ['B_5783']
@> PRO232 O_3784 A GLN254 NE2_4134 A 4.736857713716978 1 ['B_5651']
@> LYS257 NZ_4186 A PHE260 N_4221 A 4.4776039351421035 1 ['B_5531']
@> LYS257 NZ_4186 A MET258 O_4195 A 2.8371094444874725 1 ['B_5531']
@> MET258 O_4195 A PHE260 N_4221 A 3.450447652117045 1 ['B_5531']
@> ALA261 O_4246 A PHE264 O_4286 A 4.055486407325268 1 ['B_5912']
@> ALA261 O_4246 A GLY266 N_4320 A 4.719878070459026 1 ['B_5912']
@> PHE264 O_4286 A GLY266 N_4320 A 3.1480817969042674 1 ['B_5912']
@> ASP282 OD2_4579 A LYS285 NZ_4621 A 4.285278404024651 1 ['B_5933']
@> SER283 N_4580 A SER283 OG_4589 A 3.0556161408135063 1 ['B_6104']
@> ASP284 O_4596 A ARG286 N_4625 A 3.8811683807843274 1 ['B_5666']
@> LYS285 O_4608 A ILE287 N_4649 A 3.7464658012585637 1 ['B_5777']
@> LEU293 O_4734 A HIS295 O_4763 A 3.9779981146300205 1 ['B_5705']
@> GLU307 N_4941 A GLU307 O_4946 A 3.286225950843918 1 ['B_5552']
@> PRO308 N_4956 A PRO308 O_4960 A 2.8163192290647725 1 ['B_5834']
@> LEU322 N_5165 A TRP327 NE1_5262 A 4.253914550152601 1 ['B_6173']

 align2__addH_1bl6.pdb 

@> 27 water bridges detected using method chain.
@> ASN23 O_405 A SER25 OG_442 A 4.2071567596180675 1 ['B_5703']
@> PHE56 N_881 A ASN97 ND2_1600 A 5.591940450326703 1 ['B_5715']
@> MET75 O_1239 A LEU83 N_1361 A 4.795592247053538 1 ['B_5721']
@> HIS77 N_1273 A HIS77 O_1278 A 2.7756401063538463 1 ['B_5724']
@> ASP98 OD2_1614 A TYR100 OH_1650 A 5.0300705760456275 1 ['B_5712']
@> GLN125 NE2_2041 A ALA306 N_4941 A 5.855642065563778 1 ['B_5751']
@> HIS139 ND1_2300 A ALA296 N_4797 A 5.0353951185582275 1 ['B_5760']
@> ILE144 N_2359 A ARG146 NH2_2416 A 4.993912093739744 1 ['B_5904']
@> LEU148 N_2431 A ASP202 OD1_3314 A 5.001687915094264 1 ['B_5766']
@> GLY167 O_2740 A ARG170 O_2775 A 4.1692432167001225 1 ['B_5778']
@> TRP184 O_2992 A ARG186 O_3037 A 4.991058104250037 1 ['B_5799']
@> TRP184 O_2992 A GLN228 NE2_3710 A 3.7877557999427616 1 ['B_5799']
@> TRP184 O_2992 A TRP204 NE1_3348 A 5.412091924570389 1 ['B_5799']
@> TRP184 O_2992 A PHE220 N_3581 A 4.75088265483373 1 ['B_5802']
@> TYR185 OH_3030 A GLU212 OE2_3464 A 3.590770112385368 1 ['B_5808']
@> ARG186 O_3037 A GLN228 NE2_3710 A 4.119094196543704 1 ['B_5799']
@> ARG186 O_3037 A TRP204 NE1_3348 A 3.5337184381328415 1 ['B_5799']
@> MET195 SD_3200 A SER290 N_4695 A 5.951985551057735 1 ['B_5865']
@> TRP204 NE1_3348 A GLN228 NE2_3710 A 6.123917128766529 1 ['B_5799']
@> CYS208 O_3398 A LEU219 N_3562 A 4.935109421279332 1 ['B_5814']
@> CYS208 O_3398 A GLU212 OE1_3463 A 4.3175670232203665 1 ['B_5814']
@> GLU212 OE1_3463 A LEU219 N_3562 A 4.700227441305368 1 ['B_5814']
@> ALA268 O_4361 A GLY273 N_4435 A 4.9592049766066335 1 ['B_5853']
@> ILE272 N_4416 A ILE272 O_4421 A 3.1057398474437616 1 ['B_5856']
@> TYR320 OH_5156 A GLN322 OE1_5183 A 4.886730809037874 1 ['B_5874']
@> TYR320 OH_5156 A GLU325 OE2_5232 A 5.30553277249326 1 ['B_5874']
@> GLN322 OE1_5183 A GLU325 OE2_5232 A 4.619458626289443 1 ['B_5874']

 align2__addH_1bmk.pdb 

@> 23 water bridges detected using method chain.
@> THR4 N_55 A ARG20 N_338 A 6.893693494782023 2 ['B_5680', 'B_5683']
@> GLN22 OE1_396 A ASN23 N_400 A 4.280234806643208 1 ['B_5689']
@> ARG64 NE_1031 A GLU68 OE1_1112 A 5.168133415460557 1 ['B_5698']
@> ALA90 N_1475 A ASN97 N_1589 A 6.004892755078974 1 ['B_5722']
@> ASP98 OD2_1614 A TYR100 OH_1650 A 4.931317977985194 1 ['B_5725']
@> HIS139 ND1_2300 A ALA296 N_4797 A 5.051524324399516 1 ['B_5746']
@> ASP147 N_2419 A LEU148 N_2431 A 2.9192795344057028 1 ['B_5755']
@> ASP147 N_2419 A ASP202 OD1_3314 A 4.552421114088638 1 ['B_5755']
@> LEU148 N_2431 A ASP202 OD1_3314 A 4.9489810062274495 1 ['B_5755']
@> TRP184 O_2992 A PHE220 N_3581 A 4.863028891544858 1 ['B_5773']
@> ARG186 O_3037 A GLN228 NE2_3710 A 4.057977082241841 1 ['B_5776']
@> ARG186 O_3037 A TRP204 NE1_3348 A 3.607929877367357 1 ['B_5776']
@> HIS196 NE2_3221 A SER248 OG_4047 A 4.477316495402126 1 ['B_5785']
@> ASN198 OD1_3253 A SER290 OG_4704 A 3.8409114803650417 1 ['B_5782']
@> VAL201 O_3293 A SER205 OG_3368 A 3.189910500311875 1 ['B_5866']
@> TRP204 NE1_3348 A GLN228 NE2_3710 A 6.121444927466068 1 ['B_5776']
@> CYS208 O_3398 A GLU212 OE1_3463 A 4.430203945644033 1 ['B_5788']
@> CYS208 O_3398 A LEU219 N_3562 A 4.933701044854664 1 ['B_5788']
@> GLU212 OE1_3463 A LEU219 N_3562 A 4.718788509776629 1 ['B_5788']
@> VAL236 O_3859 A LEU288 N_4664 A 5.696463025422007 1 ['B_5809']
@> GLN322 OE1_5183 A GLU325 OE2_5232 A 4.97646199623789 1 ['B_5836']
@> ASP328 OD1_5278 A LEU329 N_5280 A 3.8412238935006138 1 ['B_5839']
@> SER336 OG_5419 A ASP340 OD2_5486 A 4.38346050512606 1 ['B_5842']

 align2__addH_1kv1.pdb 

@> 33 water bridges detected using method chain.
@> ARG2 NH2_38 A PHE5 N_69 A 5.02812032473369 1 ['B_5861']
@> HIS77 O_1276 A VAL80 O_1322 A 2.7861494934766085 1 ['B_5708']
@> THR88 OG1_1453 A ASP98 N_1601 A 3.9054006196547877 1 ['B_5717']
@> THR88 OG1_1453 A GLU95 O_1557 A 5.680020158414936 1 ['B_5717']
@> GLU95 O_1557 A ASP98 N_1601 A 5.269118616998484 1 ['B_5717']
@> ASN111 ND2_1811 A SER151 N_2484 A 3.5246903410086987 1 ['B_5771']
@> ASN111 ND2_1811 A SER151 OG_2493 A 4.854057581034654 1 ['B_5771']
@> ILE144 N_2357 A ARG146 NH2_2414 A 4.300001279069577 1 ['B_5759']
@> LEU148 N_2429 A ASP202 OD1_3312 A 4.794206295102458 1 ['B_5762']
@> LEU148 O_2434 A ARG186 NH1_3048 A 6.499265035371305 1 ['B_5765']
@> SER151 N_2484 A SER151 OG_2493 A 3.050507662668626 1 ['B_5771']
@> ASP165 N_2700 A PHE166 N_2712 A 2.866771180265354 1 ['B_5777']
@> TRP184 O_2990 A PHE220 N_3579 A 4.8026985122949375 1 ['B_5789']
@> ARG186 O_3035 A GLN228 NE2_3708 A 3.9755485156139128 1 ['B_5786']
@> ARG186 O_3035 A TRP204 NE1_3346 A 3.6924156049935637 1 ['B_5786']
@> ALA187 N_3054 A SER205 OG_3366 A 4.985872441208256 1 ['B_5792']
@> ALA187 N_3054 A VAL201 O_3291 A 4.755973717336968 1 ['B_5792']
@> ASN198 OD1_3251 A SER290 OG_4698 A 3.8289939932050077 1 ['B_5795']
@> VAL201 O_3291 A SER205 OG_3366 A 3.2456053364511166 1 ['B_5792']
@> TRP204 NE1_3346 A GLN228 NE2_3708 A 6.032312409018614 1 ['B_5786']
@> CYS208 O_3396 A GLU212 OE1_3461 A 4.130862621777687 1 ['B_5798']
@> CYS208 O_3396 A LEU219 N_3560 A 4.823147831033172 1 ['B_5798']
@> GLU212 OE1_3461 A LEU219 N_3560 A 4.543429211509741 1 ['B_5798']
@> THR238 OG1_3883 A PRO239 O_3893 A 4.541560634847891 1 ['B_5828']
@> LEU288 O_4663 A SER290 N_4689 A 3.224004187342195 1 ['B_5840']
@> LEU288 O_4663 A SER290 OG_4698 A 5.5931881784899735 1 ['B_5840']
@> SER290 N_4689 A SER290 OG_4698 A 2.984812389414114 1 ['B_5840']
@> LEU300 O_4843 A ALA301 O_4862 A 4.08118181413178 1 ['B_5843']
@> ALA306 N_4935 A GLN307 N_4945 A 2.7603356679940227 1 ['B_5741']
@> GLU314 O_5055 A PRO315 N_5065 A 2.235735673106285 1 ['B_5744']
@> GLU314 O_5055 A PRO315 O_5069 A 3.0718771134275555 1 ['B_5744']
@> PRO315 N_5065 A PRO315 O_5069 A 2.887335276686792 1 ['B_5744']
@> LEU329 N_5274 A TRP334 NE1_5371 A 4.184205778878471 1 ['B_5852']
```

**Review by karolamik13 — APPROVED** [review]
Looks good. For WatFinder, we would like to remove only those that don't contain water at all, but it is nice to have an option for how much water we want.

The new functions are working nicely.

**Comment by jamesmkrieger** [comment]
Great

**Pull request merged**
