### PR TITLE
fix multiprocessing output

### PR DESCRIPTION
**Pull request by jamesmkrieger**
This fixes the problem with the last implementation of calcWaterBridgesTrajectory that didn't actually output the results

### CODE REVIEW

**Review by karolamik13 — COMMENTED** [review]
I tested different WatFinder functions.

Issues:
(1) when I tested: 
waterBridges = calcWaterBridgesTrajectory(coords_traj, trajectory, method='chain')

The order of checking frames is odd:
@> Frame: 0
@> Frame: 1
@> Frame: 2
@> Frame: 3
@> Frame: 4
@> Frame: 5
@> Frame: 6
@> Frame: 7
@> Frame: 8
@> Frame: 10
@> Frame: 13
@> Frame: 12
@> Frame: 9
@> Frame: 11
@> Frame: 14
@> Frame: 15
@> Frame: 16
@> Frame: 17
@> Frame: 19
@> Frame: 18
@> Frame: 20
@> Frame: 22
@> Frame: 21
@> Frame: 23
@> Frame: 25
@> Frame: 24
@> Frame: 26
@> Frame: 27
@> Frame: 28
@> Frame: 29
@> Frame: 30
@> Frame: 31
@> Frame: 33
@> Frame: 32
@> Frame: 34
@> Frame: 35
@> Frame: 36
@> Frame: 37
@> Frame: 38
@> Frame: 39
@> Frame: 40
@> Frame: 41
@> Frame: 42
@> Frame: 44
@> Frame: 43
@> Frame: 46
@> Frame: 45
@> Frame: 47
@> Frame: 48
@> Frame: 49
@> Frame: 50
@> 99 water bridges detected using method chain.
@> 89 water bridges detected using method chain.
@> 48 water bridges detected using method chain.
@> 109 water bridges detected using method chain.
@> 107 water bridges detected using method chain.
@> 100 water bridges detected using method chain.
@> 114 water bridges detected using method chain.
@> 98 water bridges detected using method chain.
@> 109 water bridges detected using method chain.
@> 117 water bridges detected using method chain.
@> 93 water bridges detected using method chain.
@> 110 water bridges detected using method chain.
@> 100 water bridges detected using method chain.
@> 94 water bridges detected using method chain.
@> 119 water bridges detected using method chain.
@> 95 water bridges detected using method chain.
@> 111 water bridges detected using method chain.
@> 94 water bridges detected using method chain.
@> 101 water bridges detected using method chain.
@> 112 water bridges detected using method chain.
@> 104 water bridges detected using method chain.
@> 101 water bridges detected using method chain.
@> 107 water bridges detected using method chain.
@> 113 water bridges detected using method chain.
@> 100 water bridges detected using method chain.
@> 89 water bridges detected using method chain.
@> 118 water bridges detected using method chain.
@> 119 water bridges detected using method chain.
@> 84 water bridges detected using method chain.
@> 96 water bridges detected using method chain.
@> 138 water bridges detected using method chain.
@> 94 water bridges detected using method chain.
@> 93 water bridges detected using method chain.
@> 116 water bridges detected using method chain.
@> 95 water bridges detected using method chain.
@> 104 water bridges detected using method chain.
@> 114 water bridges detected using method chain.
@> 116 water bridges detected using method chain.
@> 120 water bridges detected using method chain.
@> 102 water bridges detected using method chain.
@> 119 water bridges detected using method chain.
@> 83 water bridges detected using method chain.
@> 89 water bridges detected using method chain.
@> 93 water bridges detected using method chain.
@> 79 water bridges detected using method chain.
@> 101 water bridges detected using method chain.
@> 93 water bridges detected using method chain.
@> 102 water bridges detected using method chain.
@> 99 water bridges detected using method chain.
@> 133 water bridges detected using method chain.
@> 90 water bridges detected using method chain.

Previously (old code) it was:
@> Frame: 0
@> 48 water bridges detected using method chain.
@> Frame: 1
@> 109 water bridges detected using method chain.
@> Frame: 2
@> 98 water bridges detected using method chain.
@> Frame: 3
@> 100 water bridges detected using method chain.
@> Frame: 4
@> 114 water bridges detected using method chain.
@> Frame: 5
@> 94 water bridges detected using method chain.
@> Frame: 6
@> 100 water bridges detected using method chain.
@> Frame: 7
@> 113 water bridges detected using method chain.
@> Frame: 8
@> 107 water bridges detected using method chain.
@> Frame: 9
@> 89 water bridges detected using method chain.
@> Frame: 10
@> 99 water bridges detected using method chain.
@> Frame: 11
@> 110 water bridges detected using method chain.
@> Frame: 12
@> 109 water bridges detected using method chain.
@> Frame: 13
@> 95 water bridges detected using method chain.
@> Frame: 14
@> 93 water bridges detected using method chain.
@> Frame: 15
@> 104 water bridges detected using method chain.
@> Frame: 16
@> 100 water bridges detected using method chain.
@> Frame: 17
@> 96 water bridges detected using method chain.
@> Frame: 18
@> 94 water bridges detected using method chain.
@> Frame: 19
@> 83 water bridges detected using method chain.
@> Frame: 20
@> 94 water bridges detected using method chain.
@> Frame: 21
@> 114 water bridges detected using method chain.
@> Frame: 22
@> 101 water bridges detected using method chain.
@> Frame: 23
@> 102 water bridges detected using method chain.
@> Frame: 24
@> 119 water bridges detected using method chain.
@> Frame: 25
@> 104 water bridges detected using method chain.
@> Frame: 26
@> 95 water bridges detected using method chain.
@> Frame: 27
@> 101 water bridges detected using method chain.
@> Frame: 28
@> 112 water bridges detected using method chain.
@> Frame: 29
@> 116 water bridges detected using method chain.
@> Frame: 30
@> 133 water bridges detected using method chain.
@> Frame: 31
@> 102 water bridges detected using method chain.
@> Frame: 32
@> 99 water bridges detected using method chain.
@> Frame: 33
@> 93 water bridges detected using method chain.
@> Frame: 34
@> 138 water bridges detected using method chain.
@> Frame: 35
@> 120 water bridges detected using method chain.
@> Frame: 36
@> 89 water bridges detected using method chain.
@> Frame: 37
@> 116 water bridges detected using method chain.
@> Frame: 38
@> 111 water bridges detected using method chain.
@> Frame: 39
@> 119 water bridges detected using method chain.
@> Frame: 40
@> 101 water bridges detected using method chain.
@> Frame: 41
@> 118 water bridges detected using method chain.
@> Frame: 42
@> 117 water bridges detected using method chain.
@> Frame: 43
@> 84 water bridges detected using method chain.
@> Frame: 44
@> 89 water bridges detected using method chain.
@> Frame: 45
@> 79 water bridges detected using method chain.
@> Frame: 46
@> 93 water bridges detected using method chain.
@> Frame: 47
@> 119 water bridges detected using method chain.
@> Frame: 48
@> 93 water bridges detected using method chain.
@> Frame: 49
@> 90 water bridges detected using method chain.
@> Frame: 50
@> 107 water bridges detected using method chain.

But other functions are showing similar results, so there is something wrong with printing (?)

(2) findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5) - this function is not working properly.

File ~/anaconda3/envs/prody/lib/python3.9/site-packages/ProDy-2.4.1-py3.9-linux-x86_64.egg/prody/proteins/waterbridges.py:1200, in findClusterCenters(file_pattern, **kwargs)
   1197 if coords_wat.shape[0] == 0:
   1198     raise ValueError('No waters were selected. You may need to align your trajectory')
-> 1200 selectedWaters.setCoords(coords_wat)
   1201 selectedWaters.setNames(['DUM']*len(selectedWaters))
   1202 selectedWaters.setResnums(range(1, len(selectedWaters)+1))

File ~/anaconda3/envs/prody/lib/python3.9/site-packages/ProDy-2.4.1-py3.9-linux-x86_64.egg/prody/atomic/atomgroup.py:522, in AtomGroup.setCoords(self, coords, label)
    518         raise ValueError('coordinates of {0} are not set'
    519                          .format(str(atoms)))
    521 try:
--> 522     checkCoords(coords, csets=True, dtype=(float, np.float32))
    523 except TypeError:
    524     raise TypeError('coords must be a numpy array or an '
    525                     'object with `getCoords` method')

File ~/anaconda3/envs/prody/lib/python3.9/site-packages/ProDy-2.4.1-py3.9-linux-x86_64.egg/prody/utilities/checkers.py:44, in checkCoords(coords, csets, natoms, dtype, name)
     40     raise ValueError(str(name) + '.ndim must be ' +
     41                      ' or '.join([str(d) for d in ndims]))
     43 elif shape[-1] != 3:
---> 44     raise ValueError(str(name) + '.shape[-1] must be 3')
     46 elif natoms and shape[-2] != natoms:
     47     raise ValueError(str(name) + '.shape[-2] must match number of atoms')

ValueError: coords.shape[-1] must be 3 

(2)

**Comment by jamesmkrieger** [comment]
(1) Yes, the order of checking is in groups and the logging gets mixed up, but the order of outputs in the list will be right. 

(2) I don't know what's wrong here. This shouldn't be related to my changes, but I can try to look at it. What's the input?

**Comment by jamesmkrieger** [comment]
Probably we should match the logging rather than printing the frames first and then the outputs

**Comment by jamesmkrieger** [comment]
We can now see this more clearly:
```
In [1]: from prody import *
   ...: 
   ...: import matplotlib.pyplot as plt
   ...: 
   ...: atoms = loadAtoms('4a0v_all_sci.ag.npz')
   ...: traj = parseDCD('4a0v_all_sci_fixed_9frames.dcd')
@> Atom group was loaded in 0.53s.
@> DCD file contains 9 coordinate sets for 707044 atoms.
@> DCD file was parsed in 0.12 seconds.
@> 72.82 MB parsed at input rate 591.34 MB/s.
@> 9 coordinate sets parsed at input rate 73 frame/s.

In [2]: selstr = 'segname PROA'

In [3]: n_frames = traj.numConfs()

In [4]: x = calcWaterBridgesTrajectory(atoms, traj, stop_frame=n_frames-1,
   ...:                                selstr=selstr, expand_selection=True)
@> Frame: 0
@> Frame: 1
@> Frame: 2
@> Frame: 3
@> Frame: 4
@> Frame: 5
@> Frame: 6
@> Frame: 7
@> Frame: 8
@> 677 water bridges detected using method chain for frame 0
@> 677 water bridges detected using method chain for frame 3
@> 598 water bridges detected using method chain for frame 2
@> 677 water bridges detected using method chain for frame 6
@> 598 water bridges detected using method chain for frame 8
@> 598 water bridges detected using method chain for frame 5
@> 552 water bridges detected using method chain for frame 1
@> 552 water bridges detected using method chain for frame 7
@> 552 water bridges detected using method chain for frame 4

In [5]: [(i, len(entry)) for i, entry in enumerate(x)]
Out[5]: 
[(0, 677),
 (1, 552),
 (2, 598),
 (3, 677),
 (4, 552),
 (5, 598),
 (6, 677),
 (7, 552),
 (8, 598)]
```

**Comment by karolamik13** [comment]
Inputs and jupyter notebook are here:
http://fizyka.umk.pl/~karolamik/mds/

This jupyter notebook is based on the previous code (before 07/25)

**Comment by jamesmkrieger** [comment]
> Inputs and jupyter notebook are here: http://fizyka.umk.pl/~karolamik/mds/
> 
> This jupyter notebook is based on the previous code (before 07/25)

Thanks. This seems to be working for me

**Comment by jamesmkrieger** [comment]
> > Inputs and jupyter notebook are here: http://fizyka.umk.pl/~karolamik/mds/
> > This jupyter notebook is based on the previous code (before 07/25)
> 
> Thanks. This seems to be working for me

Oh, actually, no it didn't. I'll have a look

**Comment by jamesmkrieger** [comment]
ok, the problem is that distC was too small, so there were no big enough clusters (with more than numC waters) with that distance

**Comment by jamesmkrieger** [comment]
The problem was with building the array that was being checked. It had an extra dimension with an empty list in it, so it didn't have shape[0] of 0. shape[0] is 1 and instead shape[1] is 0.

**Comment by jamesmkrieger** [comment]
Now it works:

```
findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=10)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=10)
      [2](vscode-notebook-cell:?execution_count=4&line=2) get_ipython().system('mv clusters_5kqm_all_sci_multi_.pdb 02_10_clusters_wb_default.pdb')

File ~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1206, in findClusterCenters(file_pattern, **kwargs)
   [1204](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1204) coords_wat = np.array([sel_waters], dtype=float)
   [1205](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1205) if coords_wat.shape[1] == 0:
-> [1206](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1206)     raise ValueError('No waters were selected. You may need to align your trajectory')
   [1208](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1208) selectedWaters.setCoords(coords_wat)
   [1209](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1209) selectedWaters.setNames(['DUM']*len(selectedWaters))

ValueError: No waters were selected. You may need to align your trajectory
```

```
findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.5, numC=10)
!mv clusters_5kqm_all_sci_multi_.pdb 05_10_clusters_wb_default.pdb

waterCenters = parsePDB('05_10_clusters_wb_default.pdb')

@> 101 atoms and 1 coordinate set(s) were parsed in 0.00s.
```

**Comment by jamesmkrieger** [comment]
And the filename option works too:
```
findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.5, numC=20, 
                   filename='05_20_clusters_wb_default.pdb')

waterCenters = parsePDB('05_20_clusters_wb_default.pdb')

@> 1 atoms and 1 coordinate set(s) were parsed in 0.00s.
```

**Comment by karolamik13** [comment]
I am checking the system for which I obtained results without any problems two weeks ago. 
I still have problem with findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5) function. 

Coordinates are parsed without any problems, but in the end, I am receiving the error:

---------------------------------------------------------------------------
_ValueError                                Traceback (most recent call last)
Cell In[24], line 1
----> 1 findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5)
      2 get_ipython().system('mv clusters_5kqm_all_sci_multi_.pdb 02_05_clusters_wb_default.pdb')

File ~/anaconda3/envs/prody/lib/python3.9/site-packages/ProDy-2.4.1-py3.9-linux-x86_64.egg/prody/proteins/waterbridges.py:1207, in findClusterCenters(file_pattern, **kwargs)
   1205 coords_wat = np.array([sel_waters], dtype=float)
   1206 if coords_wat.shape[1] == 0:
-> 1207     raise ValueError('No waters were selected. You may need to align your trajectory')
   1209 selectedWaters.setCoords(coords_wat)
   1210 selectedWaters.setNames(['DUM']*len(selectedWaters))

ValueError: No waters were selected. You may need to align your trajectory  

------------------------------------------------------------------_

It is the same for all parameters I am using. I tested five different.
The trajectory is aligned, and exactly this system was working fine before applying changes to the code.

**Comment by jamesmkrieger** [comment]
can you tell me which old code you mean? I can find a version without the parallel changes and with saveWaterBridgesTrajectory and findClusterCenters on my branch https://github.com/jamesmkrieger/ProDy/tree/sel_numChains that is 12 commits behind the main ProDy, and this is also having problems

```
findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[24], [line 1](vscode-notebook-cell:?execution_count=24&line=1)
----> [1](vscode-notebook-cell:?execution_count=24&line=1) findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5)
      [2](vscode-notebook-cell:?execution_count=24&line=2) get_ipython().system('mv clusters_5kqm_all_sci_multi_.pdb 02_05_clusters_wb_default.pdb')

File ~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1143, in findClusterCenters(file_pattern, **kwargs)
   [1140](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1140) if coords_wat.shape[0] == 0:
   [1141](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1141)     raise ValueError('No waters were selected. You may need to align your trajectory')
-> [1143](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1143) selectedWaters.setCoords(coords_wat)
   [1144](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1144) selectedWaters.setNames(['DUM']*len(selectedWaters))
   [1145](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/proteins/waterbridges.py:1145) selectedWaters.setResnums(range(1, len(selectedWaters)+1))

File ~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:522, in AtomGroup.setCoords(self, coords, label)
    [518](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:518)         raise ValueError('coordinates of {0} are not set'
    [519](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:519)                          .format(str(atoms)))
    [521](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:521) try:
--> [522](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:522)     checkCoords(coords, csets=True, dtype=(float, np.float32))
    [523](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:523) except TypeError:
    [524](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:524)     raise TypeError('coords must be a numpy array or an '
    [525](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/atomic/atomgroup.py:525)                     'object with `getCoords` method')

File ~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:44, in checkCoords(coords, csets, natoms, dtype, name)
     [40](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:40)     raise ValueError(str(name) + '.ndim must be ' +
     [41](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:41)                      ' or '.join([str(d) for d in ndims]))
     [43](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:43) elif shape[-1] != 3:
---> [44](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:44)     raise ValueError(str(name) + '.shape[-1] must be 3')
     [46](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:46) elif natoms and shape[-2] != natoms:
     [47](https://vscode-remote+wsl-002bubuntu-002dd.vscode-resource.vscode-cdn.net/mnt/c/Users/jkrieger/OneDrive/Documents/MC_fellowship/4_other_systems/11_vmat/~/software/scipion3/software/em/prody-github/ProDy/prody/utilities/checkers.py:47)     raise ValueError(str(name) + '.shape[-2] must match number of atoms')

ValueError: coords.shape[-1] must be 3
```

**Comment by jamesmkrieger** [comment]
ok, it looks like https://github.com/fdoljanin/ProDy/tree/master is also 12 commits behind the main so that's a good starting point

**Comment by jamesmkrieger** [comment]
Even going back to https://github.com/jamesmkrieger/ProDy/tree/streamline_fix_filter that is 22 commits behind still gives problems with `distC=0.2, numC=4`, but not with `distC=0.2, numC=3`

**Comment by jamesmkrieger** [comment]
Even with 4 month old code in https://github.com/jamesmkrieger/ProDy/tree/jmk_watFinder, which is 66 commits behind main, I'm still getting the same error.

Here is a minimal notebook: https://1drv.ms/u/s!AnOJ8_qF-DUToYpOMLk-H5KQEKSzAw?e=oOaHgg

**Comment by karolamik13** [comment]
I went back to different versions, and you are right, James, that findClusterCenters() is not working there as well. I don't know why because I kept updating versions of ProDy and testing the most current ones, and the one I had two weeks ago was working well.
I will check in the code too what may cause the problem.

**Comment by jamesmkrieger** [comment]
could there be some difference in the trajectory or something like that?

**Comment by karolamik13** [comment]
No, but I suspect that I had additional files which were analyzed by mistake. I cannot see any other explanation. I have checked that the code is working fine when we have more frames and for other systems that I analyzed previously.

**Review by karolamik13 — APPROVED** [review]
After all changes, the code is working correctly.

>> waterBridges = calcWaterBridgesTrajectory(coords_traj, trajectory, method='chain')
@> Frame: 0
@> Frame: 1
@> Frame: 2
@> Frame: 3
@> Frame: 4
@> Frame: 5
@> 48 water bridges detected using method chain for frame 1
@> 48 water bridges detected using method chain for frame 0
@> 48 water bridges detected using method chain for frame 2
@> 48 water bridges detected using method chain for frame 3
@> 48 water bridges detected using method chain for frame 5
@> 48 water bridges detected using method chain for frame 4
@> Frame: 6
@> Frame: 7
@> Frame: 8
@> Frame: 9
@> Frame: 10
@> Frame: 11
@> 80 water bridges detected using method chain for frame 6
@> 80 water bridges detected using method chain for frame 8
@> 80 water bridges detected using method chain for frame 10
@> 80 water bridges detected using method chain for frame 9
@> 80 water bridges detected using method chain for frame 11
@> 80 water bridges detected using method chain for frame 7
..


>> findClusterCenters('5kqm_all_sci_multi_*.pdb', distC=0.2, numC=5)

..
@> 2725 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 2725 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 2716 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 2717 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 2717 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> 2716 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> Results are saved in clusters_5kqm_all_sci_multi_.pdb.

**Comment by jamesmkrieger** [comment]
> No, but I suspect that I had additional files which were analyzed by mistake. I cannot see any other explanation. I have checked that the code is working fine when we have more frames and for other systems that I analyzed previously.

Ah, ok

**Pull request merged**
