### PR TITLE
Integration with py3Dmol

### PR DESCRIPTION
**Pull request by dkoes**
If py3Dmol has been imported (e.g., within a Jupyter notebook, which is the only place it makes sense), then showProtein will render using py3Dmol instead of matplotlib.

For example, see:
http://mscbio2025.csb.pitt.edu/notes/prody1.slides.html#/43

### CODE REVIEW

**Comment by dkoes** [comment]
An example notebook can be found here:
http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/9c8915f68d38db62bd9600854716f42eda4aeb1f/py3Dmol/prody.ipynb

**Comment by cihankayacihan** [comment]
I am not sure why but there is an issue related to Java in example notebook. I can not visualize the structures.

**Comment by dkoes** [comment]
Since there is no Java, I do not think you are having issues with it.  What browser/OS are you using?

**Comment by cihankayacihan** [comment]
I am sorry. I mean Javascript. I tried in Chrome Version 53.0.2785.116 (64-bit), Version 9.1.2 (11601.7.7).

**Pull request merged**
