### PR TITLE
Clustenm app

### PR DESCRIPTION
**Pull request by jamesmkrieger**
This app can run ClustENM and save the outputs in pdb and ens.npz files. 

Example command:
```
prody clustenm Runs/000002_ProDySelect/4ake_atoms.pdb --ngens 2 --number-of-modes 3 --nconfs 5 --rmsd 1. -c 15.0 -g 1.0 --maxclust "(2, 3)" --threshold "None" --solvent imp --force_field None --ionicStrength 0.0 --padding 1.0 --temp 303.15 --t_steps_i 1000 --t_steps_g 7500 --tolerance 10.0 --maxIterations 0 -P 6 -o Runs/000089_ProDyClustENM/clustenm_1 --file-prefix pdbs --no-sim --turbo --outlier --mzscore 3.5
```

Outputs:
```
(scipion3) jkrieger@whipple ~/ScipionUserData/projects/TestProDyClustENM $ ls -ltrah Runs/000089_ProDyClustENM/clustenm_1/
total 1.2M
drwxr-xr-x 2 jkrieger jkrieger 4.0K Aug  9 16:37 pdbs
-rw-r--r-- 1 jkrieger jkrieger 1.2M Aug  9 16:37 pdbs.ens.npz
drwxr-xr-x 3 jkrieger jkrieger 4.0K Aug  9 16:37 .
drwxr-xr-x 5 jkrieger jkrieger 4.0K Aug  9 16:37 ..
(scipion3) jkrieger@whipple ~/ScipionUserData/projects/TestProDyClustENM $ ls -ltrah Runs/000089_ProDyClustENM/clustenm_1/pdbs
total 1.6M
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 0_0.pdb
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 1_0.pdb
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 1_1.pdb
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 2_0.pdb
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 2_1.pdb
drwxr-xr-x 2 jkrieger jkrieger 4.0K Aug  9 16:37 .
-rw-r--r-- 1 jkrieger jkrieger 265K Aug  9 16:37 2_2.pdb
```

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
I need to remove thread pool limits because they don’t work, probably they’re applying limits on function calls and not the downstream functions where it matters

**Comment by kaynakb** [comment]
Hi James,

The following line contradicts with the definition and usage of the outlier parameter. Please see the original doc therefore:

('no_outlier', 'whether to not exclude conformers detected as outliers in each generation when using explicit solvent', False)

The original definition is:

:arg outlier: Exclusion of conformers detected as outliers in each generation.
    Default is True for implicit solvent. Outliers, if any, are detected by
    the modified z-scores of the conformers' potential energies over a generation.
    Note: It is automatically set to False when explicit solvent model is being used.
:type outlier: bool

As it is pointed out in the Note above, if the solvent model is chosen as an explicit one, then this parameter is gonna be set to False. The choice whether to use it or not is available when the solvent model is implicit.

Thank you,

Burak

**Comment by jamesmkrieger** [comment]
Thanks. Good catch. It should say implicit solvent then, not explicit.

The rest is on purpose. We can only use booleans in the apps to set something to true, so if we want to change from a default of true then we set the negative to true instead

**Comment by jamesmkrieger** [comment]
Addresses #1722

**Pull request merged**
