### PR TITLE
Added Hybrid 36 format handling

### PR DESCRIPTION
**Pull request by jamesmkrieger**
This should follows how I understand this format. See http://cci.lbl.gov/hybrid_36/

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
I took into account the comment from #828 and put a warning here too. I also have in my master fork a version that combines the two sets of changes. I guess it probably makes sense to make a new devel fork and pull request with both actually because they are accumulating conflicts.

**Comment by SHZ66** [comment]
The changes look good - but they are very low-level so we will want to test them on a few cases.

**Comment by jamesmkrieger** [comment]
I agree. Let's test them further before merging.

**Comment by jamesmkrieger** [comment]
I've just cleaned them up and tested them and made some fixes and I think we should be good to go. 

There are now 2 options for how to treat serial numbers above 99999, and we get warnings when they come into play. Most PDB files don't have high enough serial numbers for this to matter but some might.

1. The original and now default option is to use hexidecimal numbers:
```
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import * 
   ...: import numpy as np 
   ...: import matplotlib.pyplot as plt 
   ...: plt.ion()                                                                                                                     

In [2]: ag = parseCIF('4v8r')                                                                                                         
@> 128780 atoms and 1 coordinate set(s) were parsed in 2.62s.

In [3]: protein = ag.protein                                                                                                          

In [4]: protein.setChids([chid[1] for chid in protein.getChids()])                                                                    

In [5]: writePDB('4v8r_protein_default', protein)                                                                                     
@> WARNING Indices are exceeding 99999 and hexadecimal format is being used
Out[5]: '4v8r_protein_default.pdb'
```
The lines at the border look as follows:
```
ATOM  99998  C  .ALA b4022     137.402   1.984  44.618  1.00 77.50         Z C
ATOM  99999  O  .ALA b4022     136.379   1.771  43.983  1.00 77.50         Z O
ATOM  186a0  CB .ALA b4022     138.807   0.674  46.114  1.00 50.00         Z C
ATOM  186a1  N  .PHE b4023     137.635   3.110  45.274  1.00 86.40         Z N
ATOM  186a2  CA .PHE b4023     136.684   4.199  45.265  1.00 86.40         Z C
ATOM  186a3  C  .PHE b4023     136.127   4.515  43.891  1.00 86.40         Z C
ATOM  186a4  O  .PHE b4023     134.926   4.685  43.725  1.00 86.40         Z O
ATOM  186a5  CB .PHE b4023     137.327   5.453  45.803  1.00 97.20         Z C
ATOM  186a6  CG .PHE b4023     137.534   5.432  47.254  1.00 97.20         Z C
ATOM  186a7  CD1.PHE b4023     136.443   5.256  48.123  1.00 97.20         Z C
```

2. The new option is to use the hybrid36 format:
```
In [6]: writePDB('4v8r_protein_h36', protein, hybrid36=True)                                                                          
@> WARNING Indices are exceeding 99999 and hybrid36 format is being used
Out[6]: '4v8r_protein_h36.pdb'
```
The lines at the border look as follows:
```
ATOM  99997  CA .ALA b4022     138.482   0.930  44.705  1.00 77.50         Z C
ATOM  99998  C  .ALA b4022     137.402   1.984  44.618  1.00 77.50         Z C
ATOM  99999  O  .ALA b4022     136.379   1.771  43.983  1.00 77.50         Z O
ATOM  A0000  CB .ALA b4022     138.807   0.674  46.114  1.00 50.00         Z C
ATOM  A0001  N  .PHE b4023     137.635   3.110  45.274  1.00 86.40         Z N
ATOM  A0002  CA .PHE b4023     136.684   4.199  45.265  1.00 86.40         Z C
ATOM  A0003  C  .PHE b4023     136.127   4.515  43.891  1.00 86.40         Z C
ATOM  A0004  O  .PHE b4023     134.926   4.685  43.725  1.00 86.40         Z O
ATOM  A0005  CB .PHE b4023     137.327   5.453  45.803  1.00 97.20         Z C
ATOM  A0006  CG .PHE b4023     137.534   5.432  47.254  1.00 97.20         Z C
ATOM  A0007  CD1.PHE b4023     136.443   5.256  48.123  1.00 97.20         Z C
ATOM  A0008  CD2.PHE b4023     138.822   5.615  47.783  1.00 97.20         Z C
ATOM  A0009  CE1.PHE b4023     136.628   5.264  49.528  1.00 97.20         Z C
ATOM  A000A  CE2.PHE b4023     139.048   5.627  49.180  1.00 97.20         Z C
ATOM  A000B  CZ .PHE b4023     137.946   5.451  50.066  1.00 97.20         Z C
```

**Comment by jamesmkrieger** [comment]
This also works with smaller selections using `renumber=True`.

**Pull request merged**
