### PR TITLE
Simplified .travis.yml

### PR DESCRIPTION
**Pull request by jamesmkrieger**

### CODE REVIEW

**Comment by simonbray** [comment]
It would be good to run the conda tests for multiple python versions as well (3.6 to 3.8)

**Comment by jamesmkrieger** [comment]
Good point. It would be good to run conda and non-conda tests for multiple versions. Do you know how to do that?

**Comment by jamesmkrieger** [comment]
I guess I'll look into Travis CI docs more

**Comment by simonbray** [comment]
> Do you know how to do that?

Not without going into the docs sorry

**Comment by jamesmkrieger** [comment]
> > Do you know how to do that?
> 
> Not without going into the docs sorry

Ok. Thanks

**Comment by simonbray** [comment]
Actually, is this necessary? The conda-forge CI tests all the builds it creates anyway. Not sure it makes sense for these tests to be run every time a PR is opened.

**Comment by jamesmkrieger** [comment]
> Actually, is this necessary? The conda-forge CI tests all the builds it creates anyway. Not sure it makes sense for these tests to be run every time a PR is opened.

Good point. I'll use this PR to simplify the .travis.yml instead then.

**Pull request merged**
