### PR TITLE
matchChains log fix

### PR DESCRIPTION
**Pull request by jamesmkrieger**
As noted in #1464, matchChains has a last line of logging that doesn't make sense if the trival match works:
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import prody

In [2]: p1 = prody.parsePDB('Runs/000002_ProtImportPdb/extra/4ake.cif')
@> WARNING Trying to parse as mmCIF file instead
@> 3459 atoms and 1 coordinate set(s) were parsed in 0.06s.

In [3]: p2 = prody.parsePDB('Runs/000039_ProtImportPdb/extra/1ake.cif')
@> WARNING Trying to parse as mmCIF file instead
@> 3804 atoms and 1 coordinate set(s) were parsed in 0.09s.

In [4]: cutoff = 90

In [5]: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)
@> Checking AtomGroup 4ake: 2 chains are identified
@> Checking AtomGroup 1ake: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain A from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@> Trying to match chains based on local sequence alignment:

In [6]: 
```

With this fix, it doesn't:
```
In [5]: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)
@> Checking AtomGroup 4ake: 2 chains are identified
@> Checking AtomGroup 1ake: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain A from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.

In [6]: 
```

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
Checks passed: https://github.com/jamesmkrieger/ProDy/actions/runs/1794993452

**Comment by jamesmkrieger** [comment]
It looks like the variable `pairwise2` is not assigned so I need to look at this again

**Comment by jamesmkrieger** [comment]
> It looks like the variable `pairwise2` is not assigned so I need to look at this again

This is about whether the import worked so that's not the problem

**Comment by jamesmkrieger** [comment]
Without the fix, we get the surprising behaviour where the trivial mapping is tried even if pwalign is set and then it tells us it's trying the sequence alignment even though there's nothing left to try:
```
In [1]: import prody
   ...: 
   ...: p1 = prody.parsePDB("4ake")
   ...: p2 = prody.parsePDB("1ake")
   ...: 
   ...: cutoff = 90
   ...: 
   ...: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff,
   ...:  pwalign=True)
@> PDB file is found in working directory (4ake.pdb.gz).
@> 3459 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> Secondary structures were assigned to 279 residues.
@> PDB file is found in working directory (1ake.pdb.gz).
@> 3804 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> Secondary structures were assigned to 306 residues.
@> Checking AtomGroup 4ake: 2 chains are identified
@> Checking AtomGroup 1ake: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain A from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@> Trying to match chains based on local sequence alignment:
```

With the fix, the trivial mapping doesn't happen if pwalign is set and otherwise sequence alignment isn't run if the trivial mapping worked and we don't have any unmatched:
```
In [1]: import prody
   ...: 
   ...: p1 = prody.parsePDB("4ake")
   ...: p2 = prody.parsePDB("1ake")
   ...: 
   ...: cutoff = 90
   ...: 
   ...: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff,
   ...:  pwalign=True)
@> PDB file is found in working directory (4ake.pdb.gz).
@> 3459 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> Secondary structures were assigned to 279 residues.
@> PDB file is found in working directory (1ake.pdb.gz).
@> 3804 atoms and 1 coordinate set(s) were parsed in 0.06s.
@> Secondary structures were assigned to 306 residues.
@> Checking AtomGroup 4ake: 2 chains are identified
@> Checking AtomGroup 1ake: 2 chains are identified
@> Trying to match chains based on local sequence alignment:
@>  Comparing Chain A from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>  Comparing Chain A from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>  Comparing Chain B from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>  Comparing Chain B from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.

In [2]: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff,
   ...:  pwalign=False)
@> Checking AtomGroup 4ake: 2 chains are identified
@> Checking AtomGroup 1ake: 2 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain A from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain A from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
@>   Comparing Chain B from 4ake (len=214) and Chain B from 1ake (len=214):
@>      Match: 214 residues match with 100% sequence identity and 100% overlap.
```

**Comment by SHZ66** [comment]
It looks good! Please double check if `pwalign` is working as intended by setting it to `True` (enforced seq-align), `False` (no seq-align), and `None` (automatic) and see if the log looks correct.

**Comment by jamesmkrieger** [comment]
I guess we need another pair where the match is more challenging. I'll try 3h5v and 3qel

**Comment by jamesmkrieger** [comment]
ok, it works:

`True` = enforced seq-align and no try at trivial mapping:
```
In [1]: import prody
   ...: 
   ...: p1 = prody.parsePDB("3h5v")
   ...: p2 = prody.parsePDB("3qel")
   ...: 
   ...: cutoff = 20
   ...: 
   ...: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)
@> PDB file is found in working directory (3h5v.pdb.gz).
@> 9392 atoms and 1 coordinate set(s) were parsed in 0.19s.
@> Secondary structures were assigned to 693 residues.
@> PDB file is found in working directory (3qel.pdb.gz).
@> 10737 atoms and 1 coordinate set(s) were parsed in 0.24s.
@> Secondary structures were assigned to 904 residues.
@> Checking AtomGroup 3h5v: 3 chains are identified
@> Checking AtomGroup 3qel: 4 chains are identified
@> Trying to match chains based on local sequence alignment:
@>  Comparing Chain A from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Match: 321 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 84% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Match: 319 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Match: 316 residues match with 28% sequence identity and 84% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Match: 321 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 84% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Match: 319 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Match: 316 residues match with 28% sequence identity and 84% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain A from 3qel (len=355):
@>      Match: 318 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain C from 3qel (len=351):
@>      Match: 317 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain D from 3qel (len=345):
@>      Match: 314 residues match with 26% sequence identity and 84% overlap.
```

`False` = no seq align and an attempt at trivial mapping that failed:
```
In [2]: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff, pwalign=False)
@> Checking AtomGroup 3h5v: 3 chains are identified
@> Checking AtomGroup 3qel: 4 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=87%).
@>   Comparing Chain A from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=90%).
@>   Comparing Chain A from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=86%).
@>   Comparing Chain A from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
@>   Comparing Chain B from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=87%).
@>   Comparing Chain B from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=90%).
@>   Comparing Chain B from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=86%).
@>   Comparing Chain B from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
@>   Comparing Chain C from 3h5v (len=373) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=88%).
@>   Comparing Chain C from 3h5v (len=373) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=91%).
@>   Comparing Chain C from 3h5v (len=373) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=87%).
@>   Comparing Chain C from 3h5v (len=373) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
```

`None` = default behaviour of trying trivial mapping and then falling back on seq align:
```
In [3]: m = prody.matchChains(p1.protein, p2.protein, subset="all", overlap=cutoff, seqid=cutoff, pwalign=None)
@> Checking AtomGroup 3h5v: 3 chains are identified
@> Checking AtomGroup 3qel: 4 chains are identified
@> Trying to match chains based on residue numbers and names:
@>   Comparing Chain A from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=87%).
@>   Comparing Chain A from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=90%).
@>   Comparing Chain A from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=86%).
@>   Comparing Chain A from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
@>   Comparing Chain B from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=87%).
@>   Comparing Chain B from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=90%).
@>   Comparing Chain B from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=86%).
@>   Comparing Chain B from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
@>   Comparing Chain C from 3h5v (len=373) and Chain A from 3qel (len=355):
@>      Failed to match chains (seqid=4%, overlap=88%).
@>   Comparing Chain C from 3h5v (len=373) and Chain B from 3qel (len=353):
@>      Failed to match chains (seqid=5%, overlap=91%).
@>   Comparing Chain C from 3h5v (len=373) and Chain C from 3qel (len=351):
@>      Failed to match chains (seqid=3%, overlap=87%).
@>   Comparing Chain C from 3h5v (len=373) and Chain D from 3qel (len=345):
@>      Failed to match chains (seqid=5%, overlap=89%).
@> Trying to match chains based on local sequence alignment:
@>  Comparing Chain A from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Match: 321 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 84% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Match: 319 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain A from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Match: 316 residues match with 28% sequence identity and 84% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain A from 3qel (len=355):
@>      Match: 321 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 84% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain C from 3qel (len=351):
@>      Match: 319 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain B from 3h5v (len=376) and Chain D from 3qel (len=345):
@>      Match: 316 residues match with 28% sequence identity and 84% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain A from 3qel (len=355):
@>      Match: 318 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain B from 3qel (len=353):
@>      Match: 316 residues match with 25% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain C from 3qel (len=351):
@>      Match: 317 residues match with 28% sequence identity and 85% overlap.
@>  Comparing Chain C from 3h5v (len=373) and Chain D from 3qel (len=345):
@>      Match: 314 residues match with 26% sequence identity and 84% overlap.
```

**Pull request merged**
