### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
### Description
Hi :wave:, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/ProDy/) that can improve the general code quality here.
This PR fixes a few of the issues detected.

### Summary of changes:
- Refactor iterating over dictionary.
- Simplify `if` statement.
- Use list comprehension instead of `list()` method.
- Add `.deepsource.toml` file.

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by jamesmkrieger** [comment]
Looks good to me

**Comment by jamesmkrieger** [comment]
Have you tested that these changes all maintain expected behaviours in both Python 2 and Python 3?

**Comment by akshgpt7** [comment]
@jamesmkrieger  Yes, the changes are consistent with both Python2 and 3.

**Comment by jamesmkrieger** [comment]
Thanks. Then I’ll merge it

**Comment by akshgpt7** [comment]
@jamesmkrieger, The issues fixed here were detected by running [DeepSource](https://deepsource.io/) analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug risks on the fly for every change made. You can also use the Autofix feature to fix them with one click.

Here's what you can do if you wish to activate DeepSource to continuously analyze your repository:
- [Install DeepSource](https://deepsource.io/dashboard) on your repository.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings.
- Activate analysis [here](https://deepsource.io/gh/prody/ProDy).

If you have any doubts or questions, you can check out the [docs](https://deepsource.io/docs/), or feel free to reach out :)

**Comment by jamesmkrieger** [comment]
Thanks

**Comment by akshgpt7** [comment]
@jamesmkrieger do you need any help with activating DeepSource?
I ask so because the `.deepsource.toml` file that you merged will only take effect if analysis is activated.

**Comment by jamesmkrieger** [comment]
Thanks for the offer. We haven’t actually decided whether to activate it yet though.

Best wishes 
James

**Pull request merged**
