### PR TITLE
fix to calcTransformation to correctly handle reflection

### PR DESCRIPTION
**Pull request by jamesmkrieger**
This fix was suggested in issue #910

### CODE REVIEW

**Comment by SHZ66** [comment]
The title should be "correctly" handle reflection. I will look at this.

**Comment by jamesmkrieger** [comment]
ok I changed the title

**Comment by SHZ66** [comment]
Yes, this is indeed a valid fix to the implementation of the Kabsch algorithm.

**Comment by SHZ66** [comment]
The only problem might be that `Vh` is already transposed right eigenvector matrix so it doesn't need to be transposed again.

**Pull request merged**
