### PR TITLE
split pqr coords by line positions when needed

### PR DESCRIPTION
**Pull request by jamesmkrieger**
Potential fix for #1855 

If the line does not have the right fields because of no spaces between coords to maintain pdb-like format, then it splits them by pdb-like positions

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
We could do with tests for this too. Currently, there aren't any for parsePQR at all

**Comment by jamesmkrieger** [comment]
I haven't merged this branch as I don't have any unit tests yet, but I guess at some point I can make them from the example snippets you gave in the issue.

**Comment by jamesmkrieger** [comment]
This has all the tests and seems to work well

**Review by atbogetti — APPROVED** [review]

**Comment by jamesmkrieger** [comment]
thank you

**Pull request merged**
